### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jeffmax** [tomhodgins/tinkerpad#1]
This is really cool, I was wondering if you might add a License file- it would make it easier to fork and modify for other uses. I am thinking about using this as part of tutorial for teaching students how to code on the raspberry pi.

**Comment by tomhodgins** [comment]
Hey Jeff,

I am travelling at the moment so I'll have to add that license when I get to my destination. I am fond of the MIT license, which basically says you must retain the existing copyright info, and you're free to do anything else with the code other than sue me because you used it ; ) Does that give you the flexibility you're after to use this as you want?

Originally I created this as an offline-capable web page I could bookmark to tinker around with HTML & CSS on my iPad when on the subway, and I still use it weekly for learning new things about JS.

Will you be using it on the Raspberry Pi as a lightweight editor, will you be having the students modify Tinkerpad itself as the learning exercise? I'm glad it's useful for more than just me!

Hope you have a great day,
Tommy

**Comment by jeffmax** [comment]
Tommy,

MIT would be great. I think if we use Tinkerpad it would be as an
environment for teaching development rather than modifying Tinkerpad itself
(although that would make for a great advanced exercise). I was looking at
a few other projects that sort of do similar things- I found Tinkerpad
through miniCodeEditor. I am looking for something that will be low
resource and easy to setup on a vanilla Raspberry PI.

I think I would like to try to modify Tinkerpad to have a separate space
for CSS and JavaScript, because it might be clearer for the students. There
is an interesting project called Editor.js, but I think it might be a
little resource intensive for the PI's browser.

Thanks for your quick response!

**Comment by tomhodgins** [comment]
Hi Jeff,

I've just added the license file, so happy hacking and hope you have a blast teaching HTML!

**Comment by jeffmax** [comment]
Thank you!
